### ISSUE TITLE
Merging this repo with hq?

### ISSUE THREAD

**Issue by iteles** [dwyl/contracts#2]
I would see contracts as being a natural part of our [hq repo](http://www.github.com/dwyl/hq), where dwylers are currently accustomed to going for info on business and future plans at dwyl.

Should we merge this into a contracts folder or is there a bigger plan for this @markwilliamfirth that can't be contained in `hq`?

FYI, I changed the name of this repo temporarily to more accurately reflect the contents and to avoid 'non-dwyl' language :wink:

**Comment by nelsonic** [comment]
I like to think of HQ as our "_one-stop-shop_" for all things "_company_" related... ✅ 
but I _can_ see the advantage of having contracts separate ... 👍 
Would second a merge with HQ in the short run and split it out if people think it merits having a separate repo laters...

**Comment by markwilliamfirth** [comment]
The original reason it was called `human-resources` is because we should maybe have a place for all employee documents. i.e. contracts, letters of proof of employment, etc. Albeit we could have called it `people` or something similar.

Agreed that in the short-term this could be merged with hq as it's unlikely to be populated with many documents as we don't currently have many employees.

**Comment by markwilliamfirth** [comment]
I've moved finance into hq
Might be good to leave this separate as an open source "contracts resource"?
